services:
  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: searxng
    ports:
      - "8089:8080"
    volumes:
      - ./searxng:/etc/searxng
      - ./custom-ui:/usr/local/searxng/searx/static/custom-ui
    environment:
      - SEARXNG_SETTINGS_PATH=/etc/searxng/settings.yml
    restart: always
