import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import mynaui from "@iconify-json/mynaui/icons.json" with { type: "json" };

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const iconsListPath = join(root, "icons.list");
const outputPath = join(root, "ui/icons/icons.generated.slint");

const VIEWBOX = mynaui.height ?? mynaui.info?.height ?? 24;

function toPascalCase(name) {
  return name
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function parseIconsList(raw) {
  return raw
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith("#"))
    .map((line) => {
      const splitAt = line.indexOf("=");
      if (splitAt === -1) {
        return { enumName: toPascalCase(line), sourceName: line };
      }
      return {
        enumName: line.slice(0, splitAt).trim(),
        sourceName: line.slice(splitAt + 1).trim(),
      };
    });
}

function rectToPath(rectTag) {
  const widthAttr = rectTag.match(/width="([^"]+)"/);
  const heightAttr = rectTag.match(/height="([^"]+)"/);
  const xAttr = rectTag.match(/x="([^"]+)"/);
  const yAttr = rectTag.match(/y="([^"]+)"/);
  const rxAttr = rectTag.match(/rx="([^"]+)"/);

  const w = parseFloat(widthAttr?.[1] || 0);
  const h = parseFloat(heightAttr?.[1] || 0);
  const x = parseFloat(xAttr?.[1] || 0);
  const y = parseFloat(yAttr?.[1] || 0);
  const rx = parseFloat(rxAttr?.[1] || 0);

  if (rx > 0) {
    return `M ${x + rx} ${y} h ${w - 2 * rx} a ${rx} ${rx} 0 0 1 ${rx} ${rx} v ${h - 2 * rx} a ${rx} ${rx} 0 0 1 -${rx} ${rx} h -${w - 2 * rx} a ${rx} ${rx} 0 0 1 -${rx} -${rx} v -${h - 2 * rx} a ${rx} ${rx} 0 0 1 ${rx} -${rx} z`;
  }
  return `M ${x} ${y} h ${w} v ${h} h -${w} z`;
}

function circleToPath(circleTag) {
  const cxAttr = circleTag.match(/cx="([^"]+)"/);
  const cyAttr = circleTag.match(/cy="([^"]+)"/);
  const rAttr = circleTag.match(/r="([^"]+)"/);

  const cx = parseFloat(cxAttr?.[1] || 0);
  const cy = parseFloat(cyAttr?.[1] || 0);
  const r = parseFloat(rAttr?.[1] || 0);

  return `M ${cx - r} ${cy} a ${r} ${r} 0 1 0 ${r * 2} 0 a ${r} ${r} 0 1 0 -${r * 2} 0 z`;
}

function svgBodyToPathCommands(body) {
  const tagRegex = /<(path|rect|circle)\b[^>]*>/g;
  let match;
  const paths = [];

  while ((match = tagRegex.exec(body)) !== null) {
    const tag = match[0];
    const type = match[1];

    if (type === "path") {
      const dAttr = tag.match(/d="([^"]+)"/);
      if (dAttr) {
        paths.push(dAttr[1]);
      }
    } else if (type === "rect") {
      paths.push(rectToPath(tag));
    } else if (type === "circle") {
      paths.push(circleToPath(tag));
    }
  }

  if (paths.length === 0) {
    throw new Error("No SVG path data found in icon body");
  }
  return paths.join(" ");
}

function escapeSlintString(value) {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function resolveIcon(sourceName) {
  const icon = mynaui.icons[sourceName];
  if (!icon) {
    throw new Error(`Missing MynaUI icon: ${sourceName}`);
  }
  if (sourceName.endsWith("-solid")) {
    throw new Error(`Refusing solid icon (use line variant): ${sourceName}`);
  }
  return icon;
}

const usedIcons = parseIconsList(readFileSync(iconsListPath, "utf8"));

const enumLines = usedIcons.map(({ enumName }) => `    ${enumName},`);

const functionLines = usedIcons.map(({ enumName, sourceName }, index) => {
  const body = resolveIcon(sourceName).body;
  const path = escapeSlintString(svgBodyToPathCommands(body));
  const kind = `ProIconKind.${enumName}`;
  const prefix = index === 0 ? "    if kind == " : "    else if kind == ";
  return `${prefix}${kind} { "${path}" }`;
});

const output = [
  "// AUTO-GENERATED by scripts/generate-icons.mjs — do not edit",
  "// Source: @iconify-json/mynaui — Myna UI Line (https://icon-sets.iconify.design/mynaui/)",
  "",
  "export enum ProIconKind {",
  ...enumLines,
  "}",
  "",
  "export global ProIconLookup {",
  "    public pure function path(kind: ProIconKind) -> string {",
  ...functionLines.map((line) => "    " + line.trim()),
  '        else { "" }',
  "    }",
  "}",
  "",
].join("\n");

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, output);
console.log(`Generated ${usedIcons.length} MynaUI icons -> ui/icons/icons.generated.slint`);
